export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  PILOTAGE =  'PILOTAGE' ,
  JURIDIQUE = 'JURIDIQUE' ,

  QSE = "QUALITÉ, SÉCURITÉ, ENVIRONNEMENT",
  
  MPO = "MANAGEMENT DE LA PERFORMANCE OPÉRATIONNELLE",
  COMMERCIALE = "GESTION COMMERCIALE",
  
  MEL = "MAINTENANCE ENGINS (LEVAGE)",
  MEF = "MAINTENANCE ENGINS FLOTTANTS",
  MER = "MAINTENANCE ENGINS ROULANTS",
  MI = "MAINTENANCE INFRASTRUCTURES",
  VD = "VRAC & DIVERS",
  MARIRTIME = "OPÉRATIONS MARITIMES- DEPA",
  SI = "SYSTÈME D'INFORMATION",
  HYDROCARBURES = "TRAITEMENT HYDROCARBURES",
  ACHATS = "ACHATS",
  RH = "RESSOURCES HUMAINES",
  RECOUVEREMENT = "RECOUVEREMENT",
  PROGRAMMATION = "PROGRAMMATION DES OPÉRATIONS",   
  PLANIFICATION = "PLANIFICATION DES OPÉRATIONS",

}
